using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;
using Sundoll.Core;
using UnityEngine;

namespace Sundoll.Presentation
{
    public enum M7StarterContentKind
    {
        MapVisual = 0,
        PieceToken = 1
    }

    /// <summary>
    /// Auditable origin record for one bundled content item. Map visuals and
    /// token images are generated by this project, so the SHA-256 covers the
    /// canonical generator specification instead of an external source file.
    /// </summary>
    public sealed class M7StarterContentRecord
    {
        public M7StarterContentRecord(
            string contentId,
            string displayName,
            M7StarterContentKind kind,
            string generatorSpecification)
        {
            if (string.IsNullOrWhiteSpace(contentId))
            {
                throw new ArgumentException("Starter content ID is required.", nameof(contentId));
            }

            ContentId = contentId;
            DisplayName = displayName ?? contentId;
            Kind = kind;
            Author = "SundollWorld";
            Source = "SundollWorld built-in procedural generator v1";
            License = "Project Original — included for use with SundollWorld";
            Attribution = "No external attribution required";
            HashScope = "canonical-generator-spec-v1";
            Sha256 = M7StarterContentHash.Compute(generatorSpecification ?? string.Empty);
        }

        public string ContentId { get; }
        public string DisplayName { get; }
        public M7StarterContentKind Kind { get; }
        public string Author { get; }
        public string Source { get; }
        public string License { get; }
        public string Attribution { get; }
        public string HashScope { get; }
        public string Sha256 { get; }
    }

    public enum M7StarterTokenShape
    {
        Circle = 0,
        Square = 1
    }

    public sealed class M7StarterPieceDefinition
    {
        public M7StarterPieceDefinition(
            string definitionId,
            string displayName,
            string colorTag,
            M7StarterTokenShape shape,
            Color32 primaryColor,
            Color32 detailColor)
        {
            DefinitionId = definitionId;
            DisplayName = displayName;
            Category = "内置中性棋子";
            Shape = shape;
            PrimaryColor = primaryColor;
            DetailColor = detailColor;
            Tags = new[]
            {
                "内置",
                "中性",
                shape == M7StarterTokenShape.Circle ? "圆形" : "方形",
                colorTag
            };
            var specification = string.Join(
                "|",
                "starter-piece-v1",
                definitionId,
                displayName,
                shape.ToString(),
                ColorKey(primaryColor),
                ColorKey(detailColor),
                M7StarterTokenRenderer.TextureSize.ToString());
            Record = new M7StarterContentRecord(
                definitionId,
                displayName,
                M7StarterContentKind.PieceToken,
                specification);
        }

        public string DefinitionId { get; }
        public string DisplayName { get; }
        public string Category { get; }
        public IReadOnlyList<string> Tags { get; }
        public M7StarterTokenShape Shape { get; }
        public Color32 PrimaryColor { get; }
        public Color32 DetailColor { get; }
        public M7StarterContentRecord Record { get; }

        private static string ColorKey(Color32 color)
        {
            return color.r + "," + color.g + "," + color.b + "," + color.a;
        }
    }

    /// <summary>
    /// The first-party Alpha pack: 43 map visuals plus twelve neutral tokens.
    /// Only stable IDs enter world data. Licence records remain presentation
    /// metadata and do not change World Schema 2.
    /// </summary>
    public sealed class M7StarterContentManifest
    {
        private readonly List<M7StarterContentRecord> records = new List<M7StarterContentRecord>();
        private readonly List<M7StarterPieceDefinition> pieceDefinitions = new List<M7StarterPieceDefinition>();
        private readonly Dictionary<string, M7StarterContentRecord> byId =
            new Dictionary<string, M7StarterContentRecord>(StringComparer.Ordinal);

        private M7StarterContentManifest()
        {
        }

        public IReadOnlyList<M7StarterContentRecord> Records => records;
        public IReadOnlyList<M7StarterPieceDefinition> PieceDefinitions => pieceDefinitions;

        public bool TryGet(string contentId, out M7StarterContentRecord record)
        {
            record = null;
            return !string.IsNullOrWhiteSpace(contentId) && byId.TryGetValue(contentId, out record);
        }

        public static M7StarterContentManifest CreateBuiltIn(IMapVisualCatalog mapCatalog = null)
        {
            mapCatalog = mapCatalog ?? new M7BuiltinMapVisualCatalog();
            var manifest = new M7StarterContentManifest();
            foreach (var definition in mapCatalog.Definitions)
            {
                if (definition == null || string.IsNullOrWhiteSpace(definition.contentId))
                {
                    continue;
                }

                var primary = (Color32)definition.primaryColor;
                var detail = (Color32)definition.detailColor;
                var specification = string.Join(
                    "|",
                    "map-visual-v1",
                    definition.contentId,
                    definition.layerId,
                    definition.displayName,
                    definition.pattern.ToString(),
                    ColorKey(primary),
                    ColorKey(detail),
                    M7BuiltinMapVisualCatalog.TextureSize.ToString());
                manifest.AddRecord(new M7StarterContentRecord(
                    definition.contentId,
                    definition.displayName,
                    M7StarterContentKind.MapVisual,
                    specification));
            }

            manifest.AddTokenPair("red", "红色", "#A94F4A", "#F0C9A0");
            manifest.AddTokenPair("blue", "蓝色", "#4D78A5", "#C6D9E8");
            manifest.AddTokenPair("green", "绿色", "#5D875F", "#D0DEC0");
            manifest.AddTokenPair("gold", "金色", "#B88942", "#F1DC9B");
            manifest.AddTokenPair("violet", "紫色", "#76628F", "#D9C9E4");
            manifest.AddTokenPair("slate", "灰色", "#68737D", "#D5D9D7");
            return manifest;
        }

        private void AddTokenPair(string idSuffix, string colorName, string primaryHtml, string detailHtml)
        {
            var primary = ParseColor(primaryHtml);
            var detail = ParseColor(detailHtml);
            AddPiece(new M7StarterPieceDefinition(
                "starter-token-circle-" + idSuffix,
                colorName + "圆形棋子",
                colorName,
                M7StarterTokenShape.Circle,
                primary,
                detail));
            AddPiece(new M7StarterPieceDefinition(
                "starter-token-square-" + idSuffix,
                colorName + "方形棋子",
                colorName,
                M7StarterTokenShape.Square,
                primary,
                detail));
        }

        private void AddPiece(M7StarterPieceDefinition definition)
        {
            pieceDefinitions.Add(definition);
            AddRecord(definition.Record);
        }

        private void AddRecord(M7StarterContentRecord record)
        {
            if (record == null)
            {
                throw new ArgumentNullException(nameof(record));
            }

            if (byId.ContainsKey(record.ContentId))
            {
                throw new InvalidOperationException("Duplicate starter content ID: " + record.ContentId);
            }

            byId.Add(record.ContentId, record);
            records.Add(record);
        }

        private static Color32 ParseColor(string value)
        {
            return ColorUtility.TryParseHtmlString(value, out var color)
                ? (Color32)color
                : new Color32(255, 0, 255, 255);
        }

        private static string ColorKey(Color32 color)
        {
            return color.r + "," + color.g + "," + color.b + "," + color.a;
        }
    }

    public static class M7StarterTokenRenderer
    {
        public const int TextureSize = 128;

        public static byte[] CreatePng(M7StarterPieceDefinition definition)
        {
            if (definition == null)
            {
                throw new ArgumentNullException(nameof(definition));
            }

            var texture = new Texture2D(TextureSize, TextureSize, TextureFormat.RGBA32, false)
            {
                name = "SundollWorld.StarterToken." + definition.DefinitionId,
                filterMode = FilterMode.Bilinear,
                wrapMode = TextureWrapMode.Clamp
            };
            try
            {
                var pixels = new Color32[TextureSize * TextureSize];
                for (var y = 0; y < TextureSize; y++)
                {
                    for (var x = 0; x < TextureSize; x++)
                    {
                        pixels[y * TextureSize + x] = PixelFor(definition, x, y);
                    }
                }

                texture.SetPixels32(pixels);
                texture.Apply(false, false);
                return texture.EncodeToPNG();
            }
            finally
            {
                if (UnityEngine.Application.isPlaying)
                {
                    UnityEngine.Object.Destroy(texture);
                }
                else
                {
                    UnityEngine.Object.DestroyImmediate(texture);
                }
            }
        }

        private static Color32 PixelFor(M7StarterPieceDefinition definition, int x, int y)
        {
            var dx = x - (TextureSize - 1) * 0.5f;
            var dy = y - (TextureSize - 1) * 0.5f;
            var inside = definition.Shape == M7StarterTokenShape.Circle
                ? dx * dx + dy * dy <= 55f * 55f
                : InsideRoundedSquare(x, y);
            if (!inside)
            {
                return new Color32(0, 0, 0, 0);
            }

            var border = definition.Shape == M7StarterTokenShape.Circle
                ? dx * dx + dy * dy >= 49f * 49f
                : x < 18 || x > TextureSize - 19 || y < 18 || y > TextureSize - 19;
            if (border)
            {
                return Blend(definition.PrimaryColor, new Color32(24, 28, 34, 255), 0.58f);
            }

            var centerMark = Math.Abs(dx) + Math.Abs(dy) < 18f;
            if (centerMark)
            {
                return definition.DetailColor;
            }

            var engraved = (x + y) % 18 < 2 && Math.Abs(dx) + Math.Abs(dy) > 28f;
            return engraved
                ? Blend(definition.PrimaryColor, definition.DetailColor, 0.18f)
                : definition.PrimaryColor;
        }

        private static bool InsideRoundedSquare(int x, int y)
        {
            const int min = 10;
            const int max = TextureSize - 11;
            const int radius = 12;
            if (x >= min + radius && x <= max - radius && y >= min && y <= max)
            {
                return true;
            }

            if (y >= min + radius && y <= max - radius && x >= min && x <= max)
            {
                return true;
            }

            var cornerX = x < TextureSize / 2 ? min + radius : max - radius;
            var cornerY = y < TextureSize / 2 ? min + radius : max - radius;
            var dx = x - cornerX;
            var dy = y - cornerY;
            return dx * dx + dy * dy <= radius * radius;
        }

        private static Color32 Blend(Color32 first, Color32 second, float amount)
        {
            return new Color32(
                (byte)Mathf.RoundToInt(Mathf.Lerp(first.r, second.r, amount)),
                (byte)Mathf.RoundToInt(Mathf.Lerp(first.g, second.g, amount)),
                (byte)Mathf.RoundToInt(Mathf.Lerp(first.b, second.b, amount)),
                255);
        }
    }

    internal static class M7StarterContentHash
    {
        public static string Compute(string value)
        {
            using (var sha = SHA256.Create())
            {
                var hash = sha.ComputeHash(Encoding.UTF8.GetBytes(value ?? string.Empty));
                var builder = new StringBuilder(hash.Length * 2);
                foreach (var valueByte in hash)
                {
                    builder.Append(valueByte.ToString("x2"));
                }

                return builder.ToString();
            }
        }
    }
}
